import { ref, computed } from 'vue';
import { buildSettingId } from '../utils/settingId.js';

export function useScriptGeneration() {
  const isGenerating = ref(false);
  const generatedScript = ref('');
  const restartActions = ref([]);
  const error = ref(null);

  const generateScript = async (selectedSettings, allSettings) => {
    isGenerating.value = true;
    error.value = null;
    
    try {
      const settingsToApply = Object.entries(selectedSettings).filter(([_, value]) => value !== undefined);
      
      if (settingsToApply.length === 0) {
        throw new Error('No settings selected to generate script');
      }

      const scriptLines = [
        '#!/usr/bin/env bash',
        '',
        '# macOS Defaults Script',
        '# Generated by ConfigKit',
        `# Generated on: ${new Date().toISOString()}`,
        '',
        'set -e',
        '',
        'echo "🍎 Configuring macOS defaults..."',
        'echo "This may take a few moments..."',
        '',
      ];

      const restartActionsSet = new Set();
      let settingsApplied = 0;

      // Group settings by domain for better organization
      const settingsByDomain = {};
      
      settingsToApply.forEach(([settingId, value]) => {
        const setting = allSettings.find(s => buildSettingId(s.domain, s.key) === settingId);
        if (!setting) return;

        const domain = setting.domain;
        if (!settingsByDomain[domain]) {
          settingsByDomain[domain] = [];
        }
        settingsByDomain[domain].push({ setting, value, settingId });
      });

      // Generate script sections by domain
      Object.entries(settingsByDomain).forEach(([domain, domainSettings]) => {
        scriptLines.push(`echo "⚙️  Configuring ${domain}..."`);
        scriptLines.push('');

        domainSettings.forEach(({ setting, value }) => {
          const command = generateDefaultsCommand(setting, value);
          if (command) {
            if (setting.title) {
              scriptLines.push(`# ${setting.title}`);
            }
            if (setting.requiresSudo) {
              scriptLines.push(`sudo ${command}`);
            } else {
              scriptLines.push(command);
            }
            scriptLines.push('');
            settingsApplied++;

            if (setting.requiresRestart) {
              restartActionsSet.add(setting.requiresRestart);
            }
          }
        });
      });

      // Add restart section if needed
      if (restartActionsSet.size > 0) {
        scriptLines.push('echo "🔄 Some changes require restart/logout:"');
        restartActionsSet.forEach(action => {
          scriptLines.push(`echo "  - ${action}"`);
        });
        scriptLines.push('');
      }

      // Add completion message
      scriptLines.push(`echo "✅ Applied ${settingsApplied} settings successfully!"`);
      
      if (restartActionsSet.size > 0) {
        scriptLines.push('echo "🚨 Please restart the required applications or log out/in for all changes to take effect."');
      } else {
        scriptLines.push('echo "🎉 All changes have been applied and are ready to use!"');
      }

      generatedScript.value = scriptLines.join('\n');
      restartActions.value = Array.from(restartActionsSet);

    } catch (err) {
      console.error('Error generating script:', err);
      error.value = err;
      generatedScript.value = '';
      restartActions.value = [];
    } finally {
      isGenerating.value = false;
    }
  };

  const generateDefaultsCommand = (setting, value) => {
    try {
      const { domain, key, parameterType } = setting;
      let command = `defaults write ${domain} ${key}`;

      // Handle different parameter types
      switch (parameterType) {
        case 'bool':
          command += ` -bool ${value ? 'true' : 'false'}`;
          break;
        case 'int':
          command += ` -int ${parseInt(value, 10)}`;
          break;
        case 'float':
          command += ` -float ${parseFloat(value)}`;
          break;
        case 'string':
        case 'text':
          // Escape quotes and special characters
          const escapedValue = String(value).replace(/"/g, '\\"').replace(/\$/g, '\\$');
          command += ` -string "${escapedValue}"`;
          break;
        case 'array':
          if (Array.isArray(value)) {
            const arrayItems = value.map(item => `"${String(item).replace(/"/g, '\\"')}"`).join(' ');
            command += ` -array ${arrayItems}`;
          } else {
            command += ` -array "${String(value).replace(/"/g, '\\"')}"`;
          }
          break;
        case 'dict':
          // For dictionaries, we'll treat the value as a string representation
          command += ` '${JSON.stringify(value)}'`;
          break;
        default:
          // Default to string if type is unknown
          const defaultEscapedValue = String(value).replace(/"/g, '\\"').replace(/\$/g, '\\$');
          command += ` "${defaultEscapedValue}"`;
      }

      return command;
    } catch (err) {
      console.warn(`Failed to generate command for ${buildSettingId(setting.domain, setting.key)}:`, err);
      return null;
    }
  };

  const downloadScript = () => {
    if (!generatedScript.value) return false;

    try {
      const blob = new Blob([generatedScript.value], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');

      link.href = url;
      link.download = 'macos-defaults.sh';
      link.style.display = 'none';

      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      return true;
    } catch (err) {
      console.error('Failed to download script:', err);
      error.value = err;
      return false;
    }
  };

  const clearScript = () => {
    generatedScript.value = '';
    restartActions.value = [];
    error.value = null;
  };

  const hasScript = computed(() => {
    return generatedScript.value.length > 0;
  });

  const scriptLineCount = computed(() => {
    return generatedScript.value.split('\n').length;
  });

  return {
    // State
    isGenerating,
    generatedScript,
    restartActions,
    error,
    
    // Computed
    hasScript,
    scriptLineCount,
    
    // Methods
    generateScript,
    downloadScript,
    clearScript
  };
}